name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Replace API URL in environment.prod.ts
        run: |
          sed -i "s|API_URL_PLACEHOLDER|${{ vars.API_URL }}|g" src/environments/environment.prod.ts

      - name: Build
        run: npm run build -- --configuration production --base-href /

      - name: Create CNAME
        run: echo "calculajuros.online" > dist/corporate/browser/CNAME

      - name: Prepare Files for GitHub Pages
        run: |
          cp dist/corporate/browser/index.html dist/corporate/browser/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/corporate/browser 
          branch: gh-pages 